---
name: remote-peer-demo
bundle_prefix:
  - ycappuccino.storage
  - ycappuccino.endpoints_storage
  - ycappuccino.endpoints_service
  - ycappuccino.http_server
  - demo
layers:
  ycappuccino_storage_memory:
    active: true
config:
  http_server:
    active: true
    port: 18160
    ip: localhost
